-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.


hl.on("hyprland.start", function()
    hl.exec_cmd 'systemctl --user start hyprland-session.target'
    hl.exec_cmd 'noctalia-shell'
end)

hl.on("config.reloaded", function()
    hl.exec_cmd("noctalia-shell")
end)

hl.on("hyprland.shutdown", function()
    os.execute("systemctl --user stop hyprland-session.target && sleep 0.1")
end)

require 'generated.local'

local mod = "SUPER"
hl.bind(mod .. " + Q", hl.dsp.window.close())
hl.bind(mod .. " + E", hl.dsp.exec_cmd("nautilus"))
hl.bind(mod .. " + Return", hl.dsp.exec_cmd("kitty"))
hl.bind(mod .. " + SHIFT + Return", hl.dsp.exec_cmd("[workspace emptyn;] kitty"))
hl.bind("ALT + SHIFT + Space", hl.dsp.focus({ workspace = "emptyn" }))
hl.bind("CTRL + SHIFT + Escape", hl.dsp.exec_cmd("kitty btop"))
hl.bind(mod .. " + M", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mod .. " + SHIFT + M", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mod .. " + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + F",
    function()
        local m = hl.get_active_monitor(); if not m then return end; hl.dispatch(hl.dsp.window.resize({
            x = math.floor(m
                .width * 65 / 100),
            y = math.floor(m.height * 65 / 100)
        }))
    end)
hl.bind(mod .. " + F", hl.dsp.window.center())
hl.bind(mod .. " + Z", hl.dsp.workspace.toggle_special("mincontainer"))
hl.bind(mod .. " + Z", hl.dsp.window.move({ workspace = "+0" }))
hl.bind(mod .. " + Z", hl.dsp.workspace.toggle_special("mincontainer"))
hl.bind(mod .. " + Z", hl.dsp.window.move({ workspace = "special:mincontainer" }))
hl.bind(mod .. " + Z", hl.dsp.workspace.toggle_special("mincontainer"))
hl.bind(mod .. " + H",
    hl.dsp.exec_cmd("/nix/store/igrv8b70m55j64dxfqw70p74gy3arbvg-toggle-transparent/bin/toggle-transparent"))
hl.bind("ALT + H", hl.dsp.focus({ direction = "left" }))
hl.bind("ALT + J", hl.dsp.focus({ direction = "down" }))
hl.bind("ALT + K", hl.dsp.focus({ direction = "up" }))
hl.bind("ALT + L", hl.dsp.focus({ direction = "right" }))
hl.bind("ALT + TAB", hl.dsp.window.cycle_next({ next = true } --[[ cyclenext: unrecognized arg(s) "visible" ]]))
hl.bind(mod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind(mod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }))
hl.bind(mod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(mod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }))
hl.bind(mod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mod .. " + 0", hl.dsp.focus({ workspace = 10 }))
hl.bind(mod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))
hl.bind("Print", hl.dsp.exec_cmd("/nix/store/6dhz2ql5yxsgd3ccfwrczkv8q0b7k3yr-screenie/bin/screenie output"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("/nix/store/6dhz2ql5yxsgd3ccfwrczkv8q0b7k3yr-screenie/bin/screenie"))
hl.bind("ALT + Space", hl.dsp.exec_cmd("noctalia-shell ipc call launcher toggle"))
hl.bind("ALT + SHIFT + Space", hl.dsp.exec_cmd("noctalia-shell ipc call launcher toggle"))
hl.bind(mod .. " + C", hl.dsp.exec_cmd("noctalia-shell ipc call launcher calculator"))
hl.bind(mod .. " + L", hl.dsp.exec_cmd("noctalia-shell ipc call lockScreen lock"))
hl.bind(mod .. " + V", hl.dsp.exec_cmd("noctalia-shell ipc call sessionMenu toggle"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("noctalia-shell ipc call volume increase"),
    { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("noctalia-shell ipc call volume decrease"),
    { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("noctalia-shell ipc call brightness increase"),
    { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("noctalia-shell ipc call brightness decrease"),
    { locked = true, repeating = true })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0"), { locked = true })
hl.bind("switch:Lid Switch", hl.dsp.exec_cmd("hyprlock"), { locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("noctalia-shell ipc call volume muteOutput"), { locked = true })

hl.bind(mod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize())

hl.env("GDK_SCALE", "2")
hl.env("XCURSOR_SIZE", "22")

hl.bind(mod .. " + R", hl.dsp.submap("resize"))
hl.define_submap("resize", function()
    hl.bind("l", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
    hl.bind("h", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
    hl.bind("k", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
    hl.bind("j", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
    hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.config({
    decoration = {
        shadow = {
            color = "rgba(19172499)",
        },
        active_opacity = 1,
        inactive_opacity = 0.900000,
        rounding = 10,
    },
    ecosystem = {
        no_donation_nag = true,
        no_update_news = true,
    },
    general = {
        border_size = 3,
        col = {
            active_border = "rgb(eb6f92)",
            inactive_border = "rgb(6e6a86)",
        },
        gaps_in = 5,
        gaps_out = 10,
        resize_on_border = true,
    },
    group = {
        groupbar = {
            col = {
                active = "rgb(eb6f92)",
                inactive = "rgb(6e6a86)",
            },
            text_color = "rgb(e0def4)",
        },
        col = {
            border_active = "rgb(eb6f92)",
            border_inactive = "rgb(6e6a86)",
            border_locked_active = "rgb(9ccfd8)",
        },
    },
    input = {
        kb_layout = "us,es",
        natural_scroll = false,
        numlock_by_default = true,
    },
    misc = {
        animate_manual_resizes = true,
        background_color = "rgb(191724)",
        disable_hyprland_logo = true,
        key_press_enables_dpms = true,
        mouse_move_enables_dpms = true,
    },
    xwayland = {
        force_zero_scaling = true,
    },
})
